version: '3.9'

services:
  client:
    build:
      dockerfile: ./Client/Dockerfile
    environment:
      - HOME=/home/node
    command: tail -f /dev/null
    volumes:
      - ./Client:/Workspace
    networks:
      - development

  api:
    build:
      dockerfile: ./API/Dockerfile
    working_dir: /Workspace
    user: vscode
    environment:
      - HOME=/home/vscode
      - DOTNET_ENVIRONMENT=Development
    command: tail -f /dev/null
    volumes:
      - ./API:/Workspace
    networks:
      - development

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    shm_size: 128mb
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_PASSWORD: developmentpass
      POSTGRES_USER: development
      POSTGRES_DB: development
      PGDATA: /data/postgres
    networks:
      - development

networks:
  development:
    driver: bridge

volumes:
  postgres: